name: Laboratorio Orca Shift Left

on: [push]

jobs:
  orca-scan:
    runs-on: ubuntu-latest
    env:
      PROJECT_KEY: "lab-principiante" # Agrupa los hallazgos en Orca

    steps:
      - name: Bajar el código
        uses: actions/checkout@v3

      # Escaneo del código (IaC, Secretos, SAST, SCA)
      - name: Escaneo de Código Orca
        uses: orca-security/shiftleft-orca-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          path: "."

      # Construir la imagen Docker
      - name: Build Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/lab-orca:latest .

      # Escaneo de la Imagen (Container Scanning)
      - name: Escaneo de Imagen Orca
        uses: orca-security/shiftleft-orca-action@v1
        with:
          api_token: ${{ secrets.ORCA_SECURITY_API_TOKEN }}
          project_key: ${{ env.PROJECT_KEY }}
          image: "${{ secrets.DOCKER_USERNAME }}/lab-orca:latest"

      # (Opcional) Subir a Docker Hub para simular "Cloud to Dev"
      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Push a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/lab-orca:latest
